### ISSUE TITLE
Doesn't work in multiplayer.

### ISSUE THREAD

**Issue by ivanproff** [SuiMachine/Star-Wars-Battlefront---Widescreen-Fix#1]
I had that problem, and I can send you source code of my LUA script if you want.

**Comment by ivanproff** [comment]
allright, its works, but not allways. 50%/50%

**Comment by ivanproff** [comment]
so, you have decompilled my trainer, right? Which version? Do you made any changes?

**Comment by SuiMachine** [comment]
Interesting that I didn't get a notification this time around on comments on my own Github. Wtf, Github. Yes, I did decompile it, I think it was newest one, but I might be wrong. If you could send me LUA (or just addresses even) that'd be a great help.

**Comment by SuiMachine** [comment]
Nope, 1.1 one. Read Width from 00728F70, calculate Height for 4:3 aspect ratio and write to 00728F74. Module is also unprotected, so it should not matter.

**Comment by ivanproff** [comment]
Strange. Do you change delay between reading and writing? It's need to be about 10 seconds to fix MP issue.
But i think it's pretty pointless now, because new update fixed this (and used same method, perhaps).

**Comment by SuiMachine** [comment]
No I don't - it's constant 1s sleep.
And yeah, we've just had a bit of a fun dissecting GOG's "fix" in PCGamingWiki Discord. Some nice potato programming.

Is it like 10s after value change? Could add 10s sleep on value change easily.

**Comment by ivanproff** [comment]
Allright, then I will share lua source code later today.

**Comment by SuiMachine** [comment]
Added 10s delay after changing resolution also modified it so it starts (what could be called as) trainer thread after it creates DirectInput device and added checks to make sure it only tries to hook battlefront.exe and nothing else (in case someone gets a really bad idea of using this dll with something else than Battlefront).

#https://github.com/SuiMachine/Star-Wars-Battlefront---Widescreen-Fix/commit/0065d601af723e9265d36c22dd8a23964d408719

**Comment by ivanproff** [comment]
My source code
https://github.com/ivanproff/SWBFarFIX-Lua-Script/blob/master/SWBFarFIX.ct

**Comment by ivanproff** [comment]
I didn't tested everything, but it seems, that latest build works pretty well.

**Comment by SuiMachine** [comment]
Cool.
